### ISSUE TITLE
Textures

### ISSUE THREAD

**Issue by Pat-Lafon** [Pat-Lafon/wgpu#11]
After #1, probably the next step in the graphics side are textures. Especially to see if there are any difference in how we need to do binding/reading any changes

**Comment by Checkmate50** [comment]
Agreed!  It might be worth going back to the design board a bit to unify our current practical approach with our previous design discussion.  The baseline texture buffer should hopefully be straightforward, but reading textures between multiple runs of the pipeline could prove difficult from the design perspective.

**Comment by Pat-Lafon** [comment]
Closed by #21
