### ISSUE TITLE
Completing binding syntax and scope

### ISSUE THREAD

**Issue by Pat-Lafon** [Pat-Lafon/wgpu#5]
Even with the `update_bind_context` macro binding is still a little arduous. There is also no sense of scope so we rely on the programmer to manage the `BIND_CONTEXT` consts. It would also be nice if the static check could be combined with the dynamic bind function in a macro.

**Comment by Checkmate50** [comment]
>  There is also no sense of scope so we rely on the programmer to manage the `BIND_CONTEXT` consts

I'm not sure I understand what this means.  Do we not use Rust's scoping with `BIND_CONTEXT`?  Are all bound variables global?  How does this interact with `new_bind_scope` (which seems relevant)?

**Comment by Pat-Lafon** [comment]
So there are actually two things going on here that I want to change. First is that the programmer needs to keep track which BIND_CONTEXT_* variables(that they create) are in use and when to use them. This is made worse by the fact that while I add scoping using `{}` in the coding examples, any of the valid programs could run without them. So it's up to the programmer to manage when each context should be used and to make sure to drop them when you are done with them so they aren't accidentally used again. Like in principle entering into a bind function should be like entering a function scope where a compiler would handle what variables are available in a function from a larger context. I'm pretty sure that rust macros are not going to be able to do this for me. Rust procedural macros might be the answer but I haven't looked enough into them yet. There are functions used like `new_bind_scope` which are brought in by one of the macros. `new_bind_scope` specifically is added by the update_bind_context macro.

**Comment by Pat-Lafon** [comment]
Closed by #21
